"use strict";
// let arr:string[]=["php" , "python" , "java" , "js" , "ts" , "node"];
// console.log(arr);
// let random:[string,number,string,boolean] = ["Sulaiman" , 19 , "abc@gmail.com" , true];
// console.log(random);
// random[2] = "xyz@gmail.com";
// console.log(random);
let random = ["Sulaiman", 19, "abc@gmail.com", true];
console.log(random);
random[3] = false;
console.log(random);
